### ISSUE TITLE
Please consider updating CRAN package

### ISSUE THREAD

**Issue by jolars** [emanuelhuber/RConics#1]
I am using RConics in my package **eulerr*. In the current R devel, I am running into errors because of a line

`as.vector(p, mode = "numeric") && length(p) == 4`

which results in errors now because the right-hand side is of longer length than one, which is no longer permitted.

I see that you've since changed this 

https://github.com/emanuelhuber/RConics/blob/b362ad91b0a79668ef59f066d560c496cf373f7c/R/cubic.R#L34) 

And that this should no longer cause any problems. Will you please consider updating RConics?

**Comment by emanuelhuber** [comment]
Hello @jolars 
Thank you for your message. I apologize for the inconvenience. I will submit RConics to Cran as soon as possible.

Best,

Emanuel

**Comment by emanuelhuber** [comment]
I just submitted the new version of RConics to CRAN... I will inform you when the update is accepted.
Best,

Emanuel

**Comment by emanuelhuber** [comment]
RConics 1.1.1 is now on CRAN.

**Comment by jolars** [comment]
Thanks a lot for the prompt action, @emanuelhuber !
